
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 30 20:34:52 CST 2021
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int OPEN_PAREN = 19;
  public static final int POWER = 8;
  public static final int CHAR = 30;
  public static final int COMMENT = 45;
  public static final int MINUS_MINUS = 10;
  public static final int INTEGER = 47;
  public static final int GREATER = 11;
  public static final int INT = 27;
  public static final int MINOR = 13;
  public static final int FOR = 34;
  public static final int MINUS = 3;
  public static final int CHARACTER = 50;
  public static final int NOT = 38;
  public static final int AND = 17;
  public static final int CLOSE_PAREN = 20;
  public static final int OR = 18;
  public static final int BOOL = 29;
  public static final int COMMA = 26;
  public static final int DIFFERENT = 16;
  public static final int PLUS = 4;
  public static final int MAIN = 46;
  public static final int IF = 41;
  public static final int DECIMAL = 48;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int PLUS_PLUS = 9;
  public static final int CLOSE_KEY = 40;
  public static final int OPEN_KEY = 39;
  public static final int EQUAL = 32;
  public static final int TRUE = 21;
  public static final int GREATER_EQUAL = 12;
  public static final int error = 1;
  public static final int NULL = 23;
  public static final int CLOSE_BRACKET = 25;
  public static final int BREAK = 44;
  public static final int OPEN_BRACKET = 24;
  public static final int MODULE = 7;
  public static final int ELSE = 42;
  public static final int CHARCHAIN = 49;
  public static final int READ = 36;
  public static final int FINAL = 33;
  public static final int FLOAT = 28;
  public static final int MULTI = 6;
  public static final int STRING = 31;
  public static final int FALSE = 22;
  public static final int MINOR_EQUAL = 14;
  public static final int ELIF = 43;
  public static final int PRINT = 37;
  public static final int EQUAL_EQUAL = 15;
  public static final int IDENTIFIER = 2;
}

